import React from "react";
import Head from 'next/head';
import MainLayout from "../components/main-layout";
import Explore from "../features/explore";
import Procedure from "../features/procedure";
import GuideUse from "../features/guide-use";
import Partners from "../features/partners";
import Contact from "../features/contact";

function Home() {
  return (
    <>
      <Head>
        <title>Page Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Explore />
      <Procedure />
      <GuideUse />
      <Partners />
      <Contact />
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}
export default Home;