import React from "react";
import Head from 'next/head';
import MainLayout from "../components/main-layout";

function Home() {
  return (
    <>
      <Head>
        <title>Page Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return <MainLayout>{page}</MainLayout>
}
export default Home;