import React from 'react';
import Head from 'next/head';
import PlanLayout from '../../components/plan-layout';

const PlanPage = () => {
    return (
        <>
            <Head>
                <title>Page Plan</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    );
};
PlanPage.getLayout = function getLayout(page) {
    return <PlanLayout>{page}</PlanLayout>
}
export default PlanPage;